# EP 1 de MAC 209
**Nomes/NUSP:**

    Ricardo Mikio Morita             5412562
    Alexandre Muller Jones           8038149
    Arthur Sakayan Vieira de Melo
    
*adicionar todos os nomes*

# To do list
(de Apêncide 1A do cap.1 do livro)

Introduction. Briefly summarize the nature of the physical system, the basic numerical method
or algorithm, and the interesting or relevant questions. OK?

Method. Describe the algorithm and how it is implemented in the program. In some cases this
explanation can be given in the program itself. Give a typical listing of your program.
Simple modifications of the program can be included in an appendix if necessary. The
program should include your name and date and be annotated in a way that is as selfexplanatory as possible. Be sure to discuss any important features of your program.

Verification of program. Confirm that your program is not incorrect by considering special cases
and by giving at least one comparison to a hand calculation or known result.

Data. Show the results of some typical runs in graphical or tabular form. Additional runs can
be included in an appendix. All runs should be labeled, and all tables and figures must
be referred to in the body of the text. Each figure and table should have a caption with
complete information, for example, the value of the time step 

Analysis. In general, the analysis of your results will include a determination of qualitative and
quantitative relationships between variables and an estimation of numerical accuracy.

Interpretation. Summarize your results and explain them in simple physical terms whenever
possible. Specific questions that were raised in the assignment should be addressed here.
Also give suggestions for future work or possible extensions. It is not necessary to answer
every part of each question in the text.

Critique. Summarize the important physical concepts for which you gained a better understanding and discuss the numerical or computer techniques you learned. Make specific
comments on the assignment and suggestions for improvements or alternatives. OK?

Log. Keep a log of the time spent on each assignment and include it with your report

# Introdução
"Briefly summarize the nature of the physical system, the basic numerical method
or algorithm, and the interesting or relevant questions"

O experimento realizado durante este primeiro Exercício-Programa(EP) buscou observar dois fenômenos plenamente descritos e bem-compreendidos: O **Movimento Retilíneo Uniforme** (MU) e o **Movimento Retilíneo Uniformemente Acelerado** (MUV).

Desprezando efeitos como atrito, a **Primeira Lei de Newton** diz que um corpo se movimentando sem a ação de uma força externa permanecerá se movendo com uma velocidade constante, descrevendo um movimento compatível com o MU. Entretanto, sob a ação de uma força constante (que se traduz em uma aceleração do objeto) de mesma direção da velocidade, como descrito pela **Segunda Lei de Newton**, teremos um aumento ou diminuição da velocidade do corpo de maneira constante que descreve o MUV.

De posse dessas observações, seguem as seguintes equações que descrevem o movimento do corpo no espaço para o MU e MUV (Notar que basta considerar $a = 0$ para obter-se as equações do MU):

| Fórmula | Observação |
|---|---|
| $$v = at + v_o$$ | $s_o$ é a posição inicial |
|$$s = s_o + v_ot _ (at^2)/2$$ | $s$ é a posição final |
|$$s = s_o + (v + v_o)/2t$$ | $v_o$ é a velocidade inicial|
|$$v^2 = v^2_o + 2a(s - s_o)$$ | $v$ é a velocidade final
|$$r = s_o + vt - (at^2)/2$$ | $a$ é a aceleração|
| $ $|$t$ é o instante de tempo |

De posse desse conhecimento, é possível fazer uma projeção do comportamento cinemático de um corpo real aplicando os dados obtidos no experimento nas equações supra- citadas e obter um modelo compatível com os resultados práticos. Entretanto, neste EP foi desenvolvido um programa que usa os dados do experimento para criar uma simulação do comportamento do corpo a partir dos dados obtidos e depois será realizada uma sobreposição da simulação com os dados reais obtidos, observando e descrevendo o resultado.

A finalidade do experimento é, portanto, de comparar o uso de simulações de computadores com os modelos teóricos já bem-definidos e comparar os resultados. A partir disso, discutir sobre a utilidade de tal ferramenta diante dos resultados.

# Método
"Describe the algorithm and how it is implemented in the program. In some cases this explanation can be given in the program itself. Give a typical listing of your program.
Simple modifications of the program can be included in an appendix if necessary. The program should include your name and date and be annotated in a way that is as self explanatory as possible. Be sure to discuss any important features of your program."

O vídeo do experimento segue no local abaixo:

(Adicionar o vídeo)

O programa e os resultados gerados estão disponíveis no seguinte repositório: https://github.com/ricardomorita42/mac0209.

Além do código escrito neste notebook, também foi usado um script python para converter os arquivos .csv numa forma em que fosse fácil plotar gráficos, substituindo as datas encontradas na primeira coluna em instantes de tempo do experimento. O código em questão está na pasta `dados/movUniforme` e `dados/movUniformVariado`, com comentários para facilitar a compreensão do mesmo.

# Verificação do Programa
"Confirm that your program is not incorrect by considering special cases
and by giving at least one comparison to a hand calculation or known result.
Data. Show the results of some typical runs in graphical or tabular form. Additional runs can
be included in an appendix. All runs should be labeled, and all tables and figures must
be referred to in the body of the text. Each figure and table should have a caption with
complete information, for example, the value of the time step."

# Dados
"Show the results of some typical runs in graphical or tabular form. Additional runs can
be included in an appendix. All runs should be labeled, and all tables and figures must
be referred to in the body of the text. Each figure and table should have a caption with
complete information, for example, the value of the time step."

## MU
Foram utilizados três celulares com a função "volta" para marcar os tempos da pessoa que realiza o experimento de andar por um trajeto pré-definido, segurando um celular com a função de acelerômetro do aplicativo **Physics Toolbox** ativada. Além disto, foi usado um celular com um tripé para filmar o experimento. O registro dos dados foi feito por uma das pessoas que marcando o tempo.

O experimento foi feito em uma superfície plana, mais especificamente entre os prédios do IME e da FAU. Na primeira parte do experimento, mediu-se o tempo do trajeto quando o transeunte passava pelas marcas 10, 20 e 30 metros, sendo que em cada marca havia uma pessoa com um cronômetro para gravar o experimento.Cada pessoa executou uma passagem pelo percurso duas vezes.

Na segunda parte do experimento, anotou-se os instantes de tempo para cada 5 metros do percurso (i.e.: Nas posições 5, 10, 15, 20, 25 e 30). Como não era possível fisicamente posicionar uma pessoa em cada sensor pela falta de pessoal e celulares, cada "sensor" gravou dois instantes, espaçados em 5 metros um do outro. Este também foi executado por cada pessoa duas vezes.

No fim do experimento de Movimento Uniforme, foram realizadas 12 travessias ao todo. Segue abaixo uma tabela com as marcas de tempo obtidas, com a Velocidade Média de cada pessoa:

In [1]:
import pandas as pd
tabela = []

In [2]:
dados = open("dados/dados_pratica_MU1.txt",'r')

for linha in dados:
    if ('#' not in linha):
        proc_linha = (linha.rstrip('\n')).split(';')
        
        vm = float(proc_linha[-1])/30
        str_vm = f"{vm:.4f}"
        proc_linha.append(str_vm)
        tabela.append(proc_linha)

resultado = pd.DataFrame(tabela, columns=["Nome","10m","20m","30m","VelMédia"])
display(resultado)

dados.close()

         Nome    10m      20m     30m VelMédia
0  Alexandre1   5.69   12.42    18.23   0.6077
1  Alexandre2   6.05    12.54   18.78   0.6260
2     Arthur1   7.11    12.14   17.16   0.5720
3     Arthur2   6.34    10.36   15.93   0.5310
4    Ricardo1   7.08    13.86   19.91   0.6637
5    Ricardo2   6.99    13.44   19.73   0.6577

In [3]:
#Calculando vel média deste experimento e salvando em variáveis
alexandre = tabela[:2]
arthur = tabela[2:4]
ricardo = tabela[4:]

vm_mu1_alexandre = (float(alexandre[0][4]) + float(alexandre[1][4]))/2
vm_mu1_arthur = (float(arthur[0][4]) + float(arthur[1][4]))/2
vm_mu1_ricardo = (float(ricardo[0][4]) + float(ricardo[1][4])) / 2

In [4]:
dados = open("dados/dados_pratica_MU2.txt",'r')
tabela = []

for linha in dados:
    if ('#' not in linha):
        proc_linha = (linha.rstrip('\n')).split(';')
        
        vm = float(proc_linha[-1])/30
        str_vm = f"{vm:.4f}"
        proc_linha.append(str_vm)
        tabela.append(proc_linha)
        
resultado = pd.DataFrame(tabela, columns=["Nome","5m","10m","15m","20m","25m","30m","Vel. Média"])
display(resultado)
dados.close()

         Nome     5m    10m     15m     20m     25m     30m Vel. Média
0  Alexandre1   2.15   4.80    8.49   11.46   14.98   18.38     0.6127
1  Alexandre2   3.22   6.13    9.20   12.30   15.50   18.64     0.6213
2     Arthur1   2.80   5.40    8.19   10.78   13.46   16.01     0.5337
3     Arthur2   3.10   5.54    7.92   10.49   11.75   15.07     0.5023
4    Ricardo1   3.80   5.40   10.50   13.75   17.15   20.57     0.6857
5    Ricardo2   3.51   7.15   10.64   14.23   15.91   19.67     0.6557

In [5]:
#Calculando vel média deste experimento e salvando em variáveis
alexandre = tabela[:2]
arthur = tabela[2:4]
ricardo = tabela[4:]

vm_mu2_alexandre = (float(alexandre[0][7]) + float(alexandre[1][7]))/2
vm_mu2_arthur = (float(arthur[0][7]) + float(arthur[1][7]))/2
vm_mu2_ricardo = (float(ricardo[0][7]) + float(ricardo[1][7]))/2

vm_alexandre = (vm_mu1_alexandre + vm_mu2_alexandre) / 2
vm_arthur = (vm_mu1_arthur + vm_mu2_arthur) / 2
vm_ricardo = (vm_mu1_ricardo + vm_mu2_ricardo) / 2

tabela = []
tabela.append(["Alexandre",f"{vm_alexandre:.4f}"])
tabela.append(["Arthur",f"{vm_arthur:.4f}"])
tabela.append(["Ricardo",f"{vm_ricardo:.4f}"])

resultado = pd.DataFrame(tabela, columns=["Nome","Vel. Média"])
display(resultado)

        Nome Vel. Média
0  Alexandre     0.6169
1     Arthur     0.5348
2    Ricardo     0.6657

## MUV

Foram utilizados três celulares ao todo neste experimento. Uma pessoa realizou o experimento de andar de bicileta por um trajeto pré-definido, enquanto segurava um celular com a função de acelerômetro do aplicativo **Physics Toolbox** ativada. Outro participante do experimento realizou a filmagem do vídeo enquanto que a cronometragem do experimento foi realizada por um terceiro aluno.

O experimento foi feito em uma superfície inclinada, mais especificamente a entrada do portão principal do Parque Villa-Lobos, cuja inclinação foi medida em dois graus. Na primeira parte do experimento, mediu-se o tempo do trajeto enquanto o ciclista passava pelas marcas 10, 20 e 30 metros. Neste experimento havia menos pessoas para executá-lo, então usou-se apenas uma pessoa com um cronômetro para gravar o experimento. O ciclista executou uma passagem pelo percurso duas vezes. Na segunda parte do experimento, anotou-se os instantes de tempo para cada 5 metros do percurso (i.e.: Nas posições 5, 10, 15, 20, 25 e 30). Este também foi executado por cada pessoa duas vezes.

In [6]:
dados = open("dados/dados_pratica_MUV1.txt",'r')
tabela = []

for linha in dados:
    if ('#' not in linha):
        tabela.append((linha.rstrip('\n')).split(';'))

resultado = pd.DataFrame(tabela, columns=["Nome","10m","20m","30m"])
display(resultado)
dados.close()

         Nome    10m    20m      30m
0  Alexandre1   4.54   8.11    11.80
1  Alexandre2   4.49   8.00   10.97

In [7]:
dados = open("dados/dados_pratica_MUV2.txt",'r')
tabela = []

for linha in dados:
    if ('#' not in linha):
        tabela.append((linha.rstrip('\n')).split(';'))

resultado = pd.DataFrame(tabela, columns=["Nome","5m","10m","15m","20m","25m","30m"])
display(resultado)
dados.close()

         Nome     5m    10m    15m    20m     25m      30m
0  Alexandre1   3.15   4.86   6.70   8.23    9.72   11.11
1  Alexandre2   3.32   5.31   7.10   8.78   10.22    11.88

# Análise
"In general, the analysis of your results will include a determination of qualitative and
quantitative relationships between variables and an estimation of numerical accuracy."

# Interpretação
"Summarize your results and explain them in simple physical terms whenever
possible. Specific questions that were raised in the assignment should be addressed here.
Also give suggestions for future work or possible extensions. It is not necessary to answer
every part of each question in the text."

# Analise crítica
"Summarize the important physical concepts for which you gained a better understanding and discuss the numerical or computer techniques you learned. Make specific
comments on the assignment and suggestions for improvements or alternatives."

Diversos problemas foram causados na medição. O tempo de reação de cada pessoa que funciona como um sensor foi notavelmente variável, não se podendo ter certeza se no Movimento Uniforme(MU) as variações nas marcações eram devidas a variações na velocidade ou se foi apenas imprecisão dos sensores. Esse é um aspecto a ser considerado e avaliado para um melhor aproveitamento e precisão das medições em futuros experimentos.

Queríamos realizar o experimento de Movimento Uniformemente Variado(MUV) com uma bicileta num declive para que pudéssemos ter maior precisão na aceleração; entretanto, só foi possível realizar este experimento na Semana Santa e não tínhamos todos os integrantes do grupo. Além disso, instabilidades no tempo nos levaram a realizar menos experimentos para que pudéssemos terminar antes que começasse a chover. Outros problemas encontrados envolveram a espera entre experimentos devido ao tráfego de transeuntes no local e um segurança do Parque perguntando o que estávamos fazendo (felizmente, já tínhamos terminado o experimento quando isto ocorreu).

Quanto a técnicas computacionais, mais uma vez, é preciso considerar no algoritmo erros como medições imprecisas e interferências externas, além, é claro, das próprias limitações computacionais, dado que a precisão infinita é algo além do poder de qualquer máquina. 

Usar a linguagem Python para realização dos cálculos facilitou a implementação do algoritmo. Houve uma certa dificuldade em se certificar de que o notebook Jupyter iria funcionar em todas as máquinas. Em um dos computadores, a instalação apenas do Jupyter não foi suficiente, pois a impressão de tabelas usou o módulo *pandas* e, mesmo usando o *pip* para instalar o Pandas, o notebook não reconheceu a instalação do módulo. No fim das contas, instalar o pacote Anaconda padronizou as instalações e facilitou o processo de usar o notebook para todos.

# Log

-  Experimento Prático: (total)
    -  Alexandre
    -  Arthur
    -  Ricardo

-  Programando: (total)
    -  Alexandre
    -  Arthur
    -  Ricardo

-  Elaboração do Reatório: (total)
    -  Alexandre
    -  Arthur
    -  Ricardo

# Contribuição dos Autores

Os três membros participaram dos experimentos, tanto como coordenadores, sensores e participantes. Todos também participaram da análise de dados coletados e da elaboração do relatório.

# Referências

https://en.wikipedia.org/wiki/Equations_of_motion#Constant_translational_acceleration_in_a_straight_line